name: Astronomer CI - Deploy DAG and dbt code to Astro

#on: 
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variable
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: DBT Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm74gkh6q037z01hqgwut2tuu
        deploy-type: dbt
        root-folder: dbt/dbtproject/
    - name: DAGs/Image Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm74gkh6q037z01hqgwut2tuu
        root-folder: astro-project/
        parse: false